# Generated by Django 4.2.21 on 2025-08-25 15:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('case_id', models.CharField(editable=False, max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('escalated', 'Escalated')], default='open', max_length=20)),
                ('topic', models.CharField(blank=True, max_length=100)),
                ('internal_notes', models.TextField(help_text='Detailed actions and decisions taken by PAAI')),
                ('customer_notes', models.TextField(blank=True, help_text='Summary notes visible to user')),
                ('resolved_by', models.CharField(blank=True, help_text='AI or human username', max_length=100)),
                ('parsed_intents', models.JSONField(blank=True, help_text='All parsed intents', null=True)),
                ('pending_intents', models.JSONField(blank=True, help_text='Pending intents', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_cases', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
