# Generated by Django 4.2.21 on 2025-08-25 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0002_agentcase_conversation_summary_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='agentcase',
            name='orchestrator_state',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
