# Generated by Django 4.2.21 on 2025-09-04 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('agent', '0003_agentcase_orchestrator_state'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toolcall',
            name='case',
        ),
        migrations.RemoveField(
            model_name='agentcase',
            name='conversation_summary',
        ),
        migrations.RemoveField(
            model_name='agentcase',
            name='last_turn_id',
        ),
        migrations.AddField(
            model_name='agentcase',
            name='ai_conversation_history',
            field=models.JSONField(blank=True, help_text='Case conversation history', null=True),
        ),
        migrations.DeleteModel(
            name='ConversationTurn',
        ),
        migrations.DeleteModel(
            name='ToolCall',
        ),
    ]
