# Generated by Django 4.2.21 on 2025-06-03 17:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodLabelScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(help_text='The uploaded image file of the pet food label.', upload_to='pet_food_labels/')),
                ('raw_text', models.TextField(blank=True, help_text='Raw text extracted from the image by the OCR engine.')),
                ('parsed_data', models.JSONField(default=dict, help_text="Parsed nutritional data and ingredients in flexible JSON format. E.g., {'calories_per_100g': 350, 'protein_percent': 30, 'ingredients': 'Chicken, Rice, etc.'}.")),
                ('ai_analysis', models.TextField(blank=True, help_text='AI-generated pros and cons summary of the pet food, based on parsed data.')),
                ('product_name', models.CharField(blank=True, help_text='User-provided or AI-extracted name of the pet food product.', max_length=255)),
                ('food_type', models.CharField(choices=[('DRY', 'Dry Food'), ('WET', 'Wet Food (Canned/Pouch)'), ('TREAT', 'Treat/Snack'), ('SUPPLEMENT', 'Supplement'), ('OTHER', 'Other')], default='OTHER', help_text='The type of pet food product (e.g., Dry, Wet, Treat).', max_length=20)),
                ('scanned_at', models.DateTimeField(default=django.utils.timezone.now, help_text='The date and time when the label was scanned.')),
                ('user', models.ForeignKey(blank=True, help_text='The user who uploaded this food label scan (optional).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='food_label_scans', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Food Label Scan',
                'verbose_name_plural': 'Food Label Scans',
                'ordering': ['-scanned_at'],
            },
        ),
    ]
