# Generated by Django 4.2.21 on 2025-06-04 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petfood_analyzer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodlabelscan',
            name='calorie_content_kcal_per_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Metabolizable Energy (ME) in kilocalories per kilogram (kcal ME/kg).', max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='foodlabelscan',
            name='calorie_content_per_unit',
            field=models.CharField(blank=True, help_text="Calorie content per familiar unit (e.g., '67 kcal ME/can', '450 kcal per cup').", max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='foodlabelscan',
            name='pet_type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('fish', 'Fish'), ('bird', 'Bird'), ('Snake, Lizards', 'Reptile'), ('other', 'Other Pet Food')], default='OTHER', help_text='The type of pet type (e.g., Dog, Cat, Bird).', max_length=20),
        ),
    ]
